# Generated by Django 2.2.13 on 2020-06-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200618_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='preparation_time',
            new_name='time',
        ),
    ]
