# Generated by Django 2.2.13 on 2020-06-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200618_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='niveau',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='teaser',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
