# Generated by Django 2.2.13 on 2020-07-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200629_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='niveau',
            field=models.CharField(choices=[('einfach', 'Einfach'), ('mittel', 'Mittel'), ('schwer', 'Schwer')], max_length=200),
        ),
    ]
