# Generated by Django 2.2.13 on 2020-07-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200706_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='niveau',
            field=models.CharField(choices=[('Niveau: Einfach', 'Einfach'), ('Niveau: Mittel', 'Mittel'), ('Niveau: Schwer', 'Schwer')], max_length=200),
        ),
    ]
