# Generated by Django 2.2.13 on 2020-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200706_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Einfach', 'Einfach'), ('Mittel', 'Mittel'), ('Schwer', 'Schwer')], max_length=200),
        ),
    ]
