# Generated by Django 2.2.13 on 2020-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200713_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Niveau: Einfach', 'Einfach'), ('Niveau: Mittel', 'Mittel'), ('Niveau: Schwer', 'Schwer')], max_length=200),
        ),
    ]
