# Generated by Django 2.2.13 on 2020-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200713_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Niveau: Einfach', 'Niveau: Einfach'), ('Niveau: Mittel', 'Niveau: Mittel'), ('Niveau: Schwer', 'Niveau: Schwer')], max_length=200),
        ),
    ]
