# Generated by Django 2.2.13 on 2020-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200714_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Einfach', 'Niveau: Einfach'), ('Mittel', 'Niveau: Mittel'), ('Schwer', 'Niveau: Schwer')], max_length=200),
        ),
    ]
