# Generated by Django 2.2.13 on 2020-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200714_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Niveau: Einfach', 'Niveau: Einfach'), ('Niveau: Mittel', 'Niveau: Mittel'), ('Niveau: Schwer', 'Niveau: Schwer')], max_length=200),
        ),
    ]
